### ISSUE TITLE
raw-socket not working anymore without root access

### ISSUE THREAD

**Issue by frankjoke** [nospaceships/node-raw-socket#53]
I use a package called net-ping which uses your package.
It worked fine even without running node as root.

For another part of the program I need also net_bind for some dhcp and I therefore set
`sudo setcap cap_net_bind_service=+eip /usr/bin/node`

Now everything works for all the other modules but your net-ping stopped working and creates
`/home/pi/ioBroker.radar/node_modules/raw-socket/index.js:47
        this.wrap = new raw.SocketWrap (
                    ^

Error: Operation not permitted
    at new Socket (/home/pi/ioBroker.radar/node_modules/raw-socket/index.js:47:14)
    at Object.exports.createSocket (/home/pi/ioBroker.radar/node_modules/raw-socket/index.js:202:9)
    at Session.getSocket (/home/pi/ioBroker.radar/node_modules/net-ping/index.js:147:20)
    at new Session (/home/pi/ioBroker.radar/node_modules/net-ping/index.js:101:7)
    at Object.exports.createSession (/home/pi/ioBroker.radar/node_modules/net-ping/index.js:545:9)
    at Object.<anonymous> (/home/pi/ioBroker.radar/test.js:226:30)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
` 
I investigated in your documentation and you were writing that you check for apple to use other protocol if the default is not working, could it be the same for linux?

Nothing else was changed from my side, so I do not know why the raw-sockets behave now differently than before!

**Comment by stephenwvickers** [comment]
Hi @frankjoke 

I believe setcap will overwrite the current capability set (at least that's what I can see):

```
[root@dev1-centos7 stephen]# getcap /usr/bin/node
/usr/bin/node = cap_net_raw+eip
[root@dev1-centos7 stephen]# setcap cap_net_bind_service=+eip /usr/bin/node
[root@dev1-centos7 stephen]# getcap /usr/bin/node
/usr/bin/node = cap_net_bind_service+eip
```

You might need something like this (I didn't test if it actually worked):

```
setcap "cap_net_raw=+eip cap_net_bind_service=+eip" /usr/bin/node
[root@dev1-centos7 stephen]# getcap /usr/bin/node
/usr/bin/node = cap_net_bind_service,cap_net_raw+eip
```

Steve

**Comment by frankjoke** [comment]
Thanks,
my final setcap is:
`sudo setcap cap_net_admin,cap_net_raw,cap_net_bind_service=+eip /usr/bin/node`

It works then well with my own written DHCP scanner (when somebody enters the network) and your net-ping (as well as with some bluetooth module like noble)!
The cap_net_admin made the difference.
