### ISSUE TITLE
Higher Node version support [feature-request]

### ISSUE THREAD

**Issue by anor731** [nospaceships/node-raw-socket#69]
```
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/home/me/Code/Pong/node_modules/raw-socket/build/Release/raw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 88. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/me/Code/Pong/node_modules/raw-socket/index.js:4:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

```

**Comment by stephenwvickers** [comment]
@anor731 If you upgrade node you will also need to reinstall/build the addon modules are they are not binary compatible with different node versions.
